### ISSUE TITLE
Bug - "Damage" in Mythic Mobs config is not carried over to MobArenaExtension

### ISSUE THREAD

**Issue by goosBanny** [SaitDev/MobArenaExtension#23]
Config:
```yaml
ZOMBIEVILL1:
  Type: ZOMBIE_VILLAGER
  Display: '&cZombie Minion'
  Faction: Undead
  Health: 25
  Damage: 16
  Drops:
   - MinionDrops
  Options:
    Profession: FARMER
    Type: SAVANNA
    KnockbackResistance: 0.75
    MovementSpeed: 0.25
```

Detail: ZOMBIEVILL1 will do 8 full hearts (16 half-hearts) of damage when outside of the Mob Arena. However, whenever it spawns inside, it will always default to vanilla damage i.e. 1 full-heart.
